import { createSlice } from "@reduxjs/toolkit";
import CardModel from "../../models/card.model";

export const initialState = {
  cards: [] as CardModel[],
};

export const cardsSlice = createSlice({
  name: "cards",
  initialState,
  reducers: {
    getAllCards: (state, action) => {
      state.cards = action.payload;
    },
    deleteCardById: (state, action) => {
      state.cards = state.cards.filter((card) => card.id !== action.payload);
    },
    getCardsByIdDocument: (state, action) => {
      state.cards = action.payload.cards;
      console.log(action.payload.cards);
    },
  },
});

// Actions generated by the slice
export const { getAllCards, deleteCardById, getCardsByIdDocument } =
  cardsSlice.actions;

//Selectors
export const cardsSelector = (state: any) => state.cards.cards;

// reducer
export default cardsSlice.reducer;
